version: '3.9'
services:
  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: titanic
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: boat
  api:
    build: ./api
    ports:
      - '8000:8000'
    environment:
      DATABASE_URL: postgresql://titanic:iceberg@database:5432/boat
  front:
    build: ./front
    ports:
      - '3000:80'
volumes:
  cache:
    driver: local
