version: '3.9'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: titanic
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: boat
volumes:
  cache:
    driver: local
